### ISSUE TITLE
Droplet.get_droplet_by_id() missing 1 required positional argument: 'droplet_id'

### ISSUE THREAD

**Issue by jaaniedasi** [digitalocean/ansible-collection#229]
### Summary

Using the `digitalocean.cloud.droplet` module to delete a droplet, I get an error about a missing parameter in the invocation of `Droplet.get_droplet_by_id()` function.

### Issue Type

Bug Report

### Component Name

plugins/modules/droplet.py#L554

### Ansible Version

```console
$ ansible --version
ansible [core 2.17.6]
  config file = /var/home/jne/.ansible.cfg
  configured module search path = ['/var/home/jne/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /var/home/jne/.local/share/pipx/venvs/ansible/lib64/python3.12/site-packages/ansible
  ansible collection location = /var/home/jne/.ansible/collections:/usr/share/ansible/collections
  executable location = /var/home/jne/.local/bin/ansible
  python version = 3.12.7 (main, Oct  1 2024, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)] (/var/home/jne/.local/share/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### Configuration

```console
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /var/home/jne/.ansible.cfg
EDITOR(env: EDITOR) = /usr/bin/nano
HOST_KEY_CHECKING(/var/home/jne/.ansible.cfg) = False

CONNECTION:
==========

paramiko_ssh:
____________
host_key_checking(/var/home/jne/.ansible.cfg) = False

ssh:
___
host_key_checking(/var/home/jne/.ansible.cfg) = False
```

### OS / Environment

Fedora Linux 40.20241108.0 (Silverblue)

### Steps to Reproduce

```yaml (paste below)
  tasks:
    - name: Get droplet info
      digitalocean.cloud.droplets_info:
        token: "{{ digitalocean_token }}"
        name: "foo"
      register: drplt

    - name: Delete droplet
      digitalocean.cloud.droplet:
        state: absent
        token: "{{ digitalocean_token }}"
        droplet_id: "{{ drplt['droplets'][0]['id'] | int }}"
```

### Expected Results

The droplet gets deleted.

### Actual Results

```console
A Python error: 

[---]
File "/tmp/ansible_digitalocean.cloud.droplet_payload_go4iw5zg/ansible_digitalocean.cloud.droplet_payload.zip/ansible_collections/digitalocean/cloud/plugins/modules/droplet.py", line 554, in absent
TypeError: Droplet.get_droplet_by_id() missing 1 required positional argument: 'droplet_id'
[---]
```

It seems that `Droplet.get_droplet_by_id()` is called without a mandatory parameter here: https://github.com/digitalocean/ansible-collection/blob/main/plugins/modules/droplet.py#L554

I tried to change code locally to this
```
droplet = self.get_droplet_by_id(self.droplet_id)
```

and this seems to have fixed the issue. Not sure if it's the proper way to solve this tho.
```


### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct
